#!/bin/sh
#
# lcg-rec-cp - Riccardo Bruno 20070725
#
# Recursive lcg copy command
#

#lcg_cp_prepare_params
lcg_cp_prepare_params()
{
      PARAMS=
      if [ -n "${LFCRECCR_VO}" ]
      then
        PARAMS=$PARAMS" --vo "$LFCRECCR_VO
      fi
      if [ -n "${LFCRECCR_CP}" ]
      then
        PARAMS=$PARAMS" lfn:"$LFCRECCR_CP/$file
      fi
      if [ -n "${LFCRECCR_LP}" ]
      then
        FILEPATH=$(echo $DIRPATH/$file" "$(pwd) |  awk '{ if(substr($1,1,1)=="/") print $1; else print $2"/"$1}')
        PARAMS=$PARAMS" file:"$FILEPATH       
      fi      
      if [ -n "${LFCRECCR_FC}" ]
      then
        export LFC_HOST=$LFCRECCR_FC
      fi
}

#parse arguments
parse_arguments()
{
  LFCRECCR_VO=
  LFCRECCR_FC=
  LFCRECCR_LP=
  LFCRECCR_CP=
  LFCRECCR_V=
  LFCRECCR_TB=
  NEEDHELP="N"
  PARAM=
  for opt in $ARGS
  do 
    OPTSIGN=$(echo ${opt} | awk '{ print substr($1,1,1) }') 
    if [ -n "${PARAM}" -a "${OPTSIGN}" != "-"  ]
    then
      case $PARAM in
        "TB" ) LFCRECCR_TB=$opt ;;
        "VO" ) LFCRECCR_VO=$opt ;;
        "LP" ) LFCRECCR_LP=$opt ;;
        "CP" ) LFCRECCR_CP=$opt ;;
        "FC" ) LFCRECCR_FC=$opt ;;        
      esac 
      PARAM=
    fi
    case $opt in
      "--tb"      | "-tb"  ) PARAM="TB"     ;;
      "--vo"      | "-vo"  ) PARAM="VO"     ;;
      "--lp"      | "-lp"  ) PARAM="LP"     ;;
      "--cp"      | "-cp"  ) PARAM="CP"     ;;
      "--fc"      | "-fc"  ) PARAM="FC"     ;;      
      "--help"    | "-h"   ) NEEDHELP="Y"   ;; 
      "--verbose" | "-v"   ) LFCRECCR_V="Y" ;;
    esac
  done
}

show_usage()
{
  echo "lcg-rec-cp"
  echo "----------"
  echo "LCG utils based recursive copy from file catalog utility"
  echo " "
  echo "Usage: `basename $0` -vo <voname> -cp <catalog_path> -lp <local_filepath> [-fc <file_catalog>] [-v]"
}

#check arguments
check_arguments()
{
  if [ "${NEEDHELP}" != "Y" ]
  then
    ERROR=
    NEWLN="\n"
    TABSP="\t"
    if [ -z "$LFCRECCR_TB" ]
    then
      LFCRECCR_TB=0
    fi
    if [ -z "${LFCRECCR_FC}" ]
    then
      if [ -n "${LFC_HOST}" ]
      then
         if [ -n "${LFCRECCR_V}" ]
         then
           ERROR=$ERROR$TABSP"Warning: Defafault LFC server: '"$LFC_HOST"' will be used"$NEWLN
         fi
      else
        ERROR=$ERROR$TABSP"LFC_HOST environment variable or -fc option must be specified with a LFC host server"$NEWLN
        NEEDHELP="Y"
      fi
    fi
    if [ -z "${LFCRECCR_VO}" ]
    then
      ERROR=$ERROR$TABSP"you must specify a virtual organization"$NEWLN
      NEEDHELP="Y"
    fi
    if [ -z "${LFCRECCR_LP}" ]
    then
      ERROR=$ERROR$TABSP"you must specify a local path"$NEWLN
      NEEDHELP="Y"
    fi
    if [ -z "${LFCRECCR_CP}" ]
    then
      ERROR=$ERROR$TABSP"you must specify a catalog path"$NEWLN
      NEEDHELP="Y"
    fi
    
    if [ -n "${ERROR}"  -a $LFCRECCR_TB -eq 0 ]
    then
      echo "Errors:"
      echo -e $ERROR    
    fi
  fi
}

calc_indlevel()
{
  LNTABS=
  if [ $LFCRECCR_TB -gt 0 ]
  then
    for t in $(seq 1 $LFCRECCR_TB)
    do
      LNTABS=$LNTABS"\t"
    done  
  fi
}

#
# lcg-rec-cp 
#

#parse the command line
if [ $# -ne 0 ]
then
  ARGS=$*
  parse_arguments
  check_arguments  
else
  NEEDHELP="Y"
fi

#view verbose summary info
if [ -n "${LFCRECCR_V}" -a "${LFCRECCR_TB}" == "0" ]
then
  echo "lcg-rec-cp"
  echo "----------"
  echo "VO          : "$LFCRECCR_VO
  echo "LFC         : "$LFCRECCR_FC
  echo "Local path  : "$LFCRECCR_LP
  echo "Catalog path: "$LFCRECCR_CP
  echo " "
fi

#view help or execute
if [ $NEEDHELP == "Y" ] 
then 
  show_usage
else
  #calculate indirection level
  calc_indlevel
  #directory or file
  FLAG=$(lfc-ls -ld ${LFCRECCR_CP} | awk '{ print substr($1,1,1) }')
  if [ "${FLAG}" == "d" ]
  then
    #create the directory in the local path
    if [ $LFCRECCR_TB -eq 0 ]
    then   
      TMPVAR=$(basename ${LFCRECCR_CP})
      DIRPATH=$(echo ${LFCRECCR_LP}/$TMPVAR | sed 's/\/\//\//g')    
    else
      DIRPATH=$(echo ${LFCRECCR_LP} | sed 's/\/\//\//g')
    fi
    #process directories first
    if [ -n "${LFCRECCR_V}" ]
    then
      echo -e $LNTABS"mkdir -p ${DIRPATH}"
    fi
    #
    # mkdir
    #
    mkdir -p ${DIRPATH}    
    SUBDIRS=$(lfc-ls -l  ${LFCRECCR_CP} | awk '{ if(substr($1,1,1)=="d") print $9 }')
    if [ -n "$SUBDIRS" ]
    then
      LFCRECCR_TB=$(($LFCRECCR_TB+1))
    fi
    for dir in $SUBDIRS
    do  
      #prepare arguments for the recursive call to $0    
      VOPT=
      if [ -n "${LFCRECCR_V}" ]
      then        
        VOPT="-v"
      fi
      FCOPT=
      if [ -n "${LFCRECCR_FC}" ]
      then        
        FCOPT="-fc "$LFCRECCR_FC
      fi
      CATALOGPATH=$(echo ${LFCRECCR_CP}/$dir | sed 's/\/\//\//g')
      LOCALPATH=$(echo ${DIRPATH}/$dir | sed 's/\/\//\//g')
      #recursive call to $0
      $0 -vo $LFCRECCR_VO $VOPT $FCOPT $SEOPT $LFCRECCR_VO -lp $LOCALPATH -cp $CATALOGPATH -tb $LFCRECCR_TB
    done
    #process files then
    FILES=$(lfc-ls -l  ${LFCRECCR_CP} | awk '{ if(substr($1,1,1)!="d" && substr($1,1,1)!="l") print $9 }')
    for file in $FILES
    do      
      #prepare PARAMS for lfc-cr
      FILE=$file
      lcg_cp_prepare_params
      if [ -n "${LFCRECCR_V}" ]
      then
        echo -e $LNTABS"lcg-cp"$PARAMS
      fi
      #
      # lcg-cp
      #
      lcg-cp $PARAMS      
    done
  elif [ "${FLAG}" != "d" -a  "${FLAG}" != "l"   ]
  then
    lcg_cp_prepare_params
    if [ -n "${LFCRECCR_V}" ]
    then
      echo -e $LNTABS"lcg-cp"$PARAMS
    fi
    #
    # lcg-cp
    #
    lcg-cp $PARAMS  
  else
    echo "Error: The local path '"$LFCRECCR_LP"' is not valid"
  fi
fi



